### ISSUE TITLE
Externe links?

### ISSUE THREAD

**Issue by moorlag** [BJOC-NL/bjoc-nl.github.io#186]
Wat doen we met externe links? Het hoofdstuk AI en robots zit er vol mee.

**Comment by moorlag** [comment]
Voorstel; we benoemen dat de bronnen Engelstalig zijn en laten het daarbij.

**Comment by aserebrenik** [comment]
LGTM

Verstuurd vanaf mijn iPhone

Op 12 nov. 2019 om 10:34 heeft Ramon Moorlag <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Voorstel; we benoemen dat de bronnen Engelstalig zijn en laten het daarbij.

**Comment by Felienne** [comment]
Voor nu dat zeker prima! Met de nieuwe financiering kunnen we er misschien een paar vertalen?
