### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by moorlag** [BJOC-NL/bjoc-nl.github.io#196]
Volgens mij begint onze eerste MVP zichtbaar te worden. @eelcodijkstra wees mij erop dat het goed is dat we in een vroegtijdig stadium al beginnen te communiceren over het product. En ik ben dat met hem eens. 

 Er is veel werk verzet, en dat moeten we delen. Wat houdt ons tegen om een eerste versie online te zetten? Op de Lander tekst en uitleg dat dit work in progress is en dat er hard gewerkt wordt. En _natuurlijk_ een link om bezoekers op te roepen om mee te vertalen. 

- Welke **uitdagingen** zijn er om de BJoC-NL online te zetten?
- Welke **eisen** worden er gesteld aan het materiaal online te zetten? 
- Klopt onze **licentie**?

**Comment by sabinev1991** [comment]
Hi Ramon,

de status is dat nu Unit 1 en 2 bijna helemaal af zijn. Van Unit 1 moeten
lessen 4 en 5 nog gedaan worden en van Unit 2 les 5. Als die zijn vertaald,
dan zijn er 2 hele hoofdstukken af maar moeten daar ook nog wel de goede
plaatjes aan worden toegevoegd. Daar kom ik helaas niet meer aan toe.

Dat is wel goed om te weten! Want, als dat gedaan is, dan heb je in ieder
geval 2 hele hoofdstukken waarmee getest kan worden :)

Groetjes,
Sabine

Op do 27 jun. 2019 om 08:05 schreef Ramon Moorlag <notifications@github.com

**Comment by moorlag** [comment]
hi @sabinev1991,
Thanks for the quick reply! 

Het is voor de zichtbaarheid en ontwikkelsnelheid volgens mij goed om 'tot zo ver zijn we' al online te zetten. Dus met Engelstalige plaatjes en her-en-der nog met wat onzorgvuldigheden qua taal, vertaling en grammatica. Wat hebben we nog nodig om het materiaal tot dus verre online te zetten?

**Comment by aserebrenik** [comment]
@moorlag "tot zover zijn we": https://drive.google.com/file/d/1NWxtMjBp8TyJ00R04i7LTkcp9uCvSDhZ/view?usp=sharing (voorbereid door @sabinev1991)  

@cfkaligula zou dit misschien je eerste stap kunnen zijn?

**Comment by CFKaligula** [comment]
Wat bedoel je precies @aserebrenik ?

**Comment by sabinev1991** [comment]
Hi Casper, ik denk dat ik het wel kan uitleggen :) het is meer een status
check en lijkt me goed als ik je vertel wat ik heb gedaan en wat handig is
als jij verder gaat waar ik ben gebleven. Het liefst hebben we zsm één
hoofdstuk (unit) helemaal af, zodat het in de praktijk alvast uitgetest kan
worden.

Ik kan je vertellen wat daar nog voor nodig is, dus mail me anders even op
sabine.verdult@gmail.com en dan plannen we een (skype)afspraak in?

Groetjes!

Op vr 28 jun. 2019 om 12:16 schreef CFKaligula <notifications@github.com>:

**Comment by moorlag** [comment]
Hebben wij trouwens een directe fork van BJC? Dan is ingebruik nemen van de website volgens mij een eitje.
